### ISSUE TITLE
Go-TFE 1.0

### ISSUE THREAD

**Issue by uturunku1** [awslabs/tecli#13]
Hi!

In a few days, HashiCorp will be releasing a major version for the [Go API client for Terraform Cloud](https://github.com/hashicorp/go-tfe/tree/main).

I am reaching out for mainly two reasons. 

First to give your team heads up that this release will contain breaking changes. We are aware that your project relies on our client and we will not want you to be caught by surprise if you decide to upgrade :)

But I also wanted to check if you'd be interested in trying out our beta version prior to the official release of 1.0. We'd love to have your feedback to find out if you were able to use this version smoothly. This pre-release version will be available very soon. Would you be able to try it out next week?

Best,
Luces

**Comment by evilensky** [comment]
Hi @uturunku1 .  It seems this project isn't very active at the moment.  May I ask, are there any plans from HCP to provide a supported / official CLI?  It's a missing piece that many of us could use in our CI systems, etc :)

**Comment by valter-silva-au** [comment]
Hi All, I've missed the notification about this thread. I will have a look into the new changes and plan a new build.
