### ISSUE TITLE
bug: make tecli/test fails

### ISSUE THREAD

**Issue by mavogel** [awslabs/tecli#4]
Hi,
great tool :) I skimmed through the contribution guideline and could not find any steps to build/test. So I dug through the Makefile and found the `tecli/test` is twice. I removed one and got the error:

```sh
make tecli/test
=== RUN   TestConfigureCmdFlags
=== RUN   TestConfigureCmdFlags/empty
FATA[0000] unable to read manual from box
exit status 1
FAIL	gitlab.aws.dev/devops-aws/tecli/tests	0.205s
make: *** [tecli/test] Error 1
```

It would be lovely to have a local working test setup if possible :)

**Comment by valter-silva-au** [comment]
Hi @mavogel, thank you for opening this issue. I've released a new version 0.2.2 which tries to solve to solve it Please let me know if the issue persists.
